# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Docker build, push & rollout (production)

on:
  push:
    branches: [ master ]

jobs:
  dockerize:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Install npm dependencies
      #   run: npm ci

      # - name: Check code style using eslint
      #   run: npm run lint

      # - name: Build server using tsc
      #   run: npm run build

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/auto-ssr:latest

      - name: Cleanup docker environment
        run: rm -rf /home/runner/.docker/config.json
